### ISSUE TITLE
BIOS 330 - no sound in kernel 1.7.0

### ISSUE THREAD

**Issue by davnozdu** [jlobue10/ALLY_Nobara_fixes#3]
I am try install kernel from RPM for old and new version BIOS.
In version for old BIOS work sound, but not work button.

For version for BIOS 323 or 330 work button but not work sound.
I am edit your install script files and recompiled kernel with all your patch but get same problem: button work - sound not work.
I am try install audio fix but this not resolve problem.

**Comment by jlobue10** [comment]
The audio fix is deprecated, and no longer recommended since the ACPI override is no longer required, and firmware is provided by linux firmware git.

If you are on 330 and plan to stay on 330 then I recommend using the latest RPMs without the v323BIOS in the file name. The difference between those RPM versions is that the ASUS kernel audio override patch in the non-v323BIOS version is disabled, since BIOS 330 has those DSD properties provided by BIOS.

N-Keys absolutely do work with those RPMs in BIOS 330 as well. What changed, is that for some reason the N-Key USB device ID is now different for the N-Key device (in BIOS 330) so this breaks HandyGCCS providing access to those side buttons. There is a [fork of HandyGCCS](https://github.com/honjow/HandyGCCS) that has a check for BIOS version that resolves this issue. LED control is lost with 330 though, unless OpenRGB has received a recent update for the same device ID change.

There are some people trying to get the Steam-patch method to be more reliable in Nobara. This is challenging but an ongoing collaborative effort. At least for now, we are able to restart the Steam-patch service in `gamescope-session` without getting kicked back to KDE Plasma, so I've reverted to usign Steam-patch with that script available if I need it. I'd susped that Steam-patch SHOULD work ok the 330 BIOS.

My brief experience with the 330 BIOS on Nobara was a mess. Auto-login was broken on most (if not all) boots. I lost LED control, which I had previously, and the last time I even booted on 330 BIOS, the system locked up for me and crashed in the LDE Plasma session. I've since reverted to version 323 and am done with 330 experiments. I'll wait for the next BIOS to try again. Hopefully this all makes sense.

**Comment by davnozdu** [comment]
Today I am install kernel + fork HandyGCCS and all work.
Thanks

**Comment by jlobue10** [comment]
Nice! I just released an updated 6.5.8 kernel that fixes the audio issues for various BIOS versions.

**Comment by davnozdu** [comment]
> Nice! I just released an updated 6.5.8 kernel that fixes the audio issues for various BIOS versions.

Super, you are hero. 
Thanks for fix.
